# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 05d0eb1a21a184607bf2979432de59310865d69f5df995658028ee6f6f78c6c3a8fed7cc5afc681f6d967377f638cc5e6612b3e119935ff00ebe0a61e8c27bf4

test:
  secret_key_base: 51243dba108472866e44db9eeca56e06ef7fb18c905cef7a3a546b4852f6821adf9a15c406c7665c3f5f34013dca32687cb4f866fb21d85a7fec1691ab3452b2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
